Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape(3, 4)
a1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a2 = a.reshape(6, 2)
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [6]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a4 = a.reshape(2, 6)
a4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [16]:
b1 = a.reshape(3, -1)
b1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
b2 = a.reshape(6, -1)
b2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [20]:
b3 = a.reshape(-1, 3)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
b4 = a.reshape(-1, 4)
b4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
b5 = a.reshape(-1, 6)
b5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [21]:
c1 = a.reshape(12, -1)
c1
# ДА

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [ ]:
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из 
нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [23]:
a = np.random.randn(3, 4)

print(a)

[[ 0.57854995 -1.06609512  1.30585479 -0.00809155]
 [ 1.89333961 -0.66619548 -1.09413814 -0.391334  ]
 [-0.98587358 -0.41862474  0.33031279 -1.13879665]]


In [25]:
a.size

12

In [27]:
a1 = a.flatten()
a1

array([ 0.57854995, -1.06609512,  1.30585479, -0.00809155,  1.89333961,
       -0.66619548, -1.09413814, -0.391334  , -0.98587358, -0.41862474,
        0.33031279, -1.13879665])

In [29]:
a1.size

12

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [36]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [53]:
a.shape


(10,)

In [54]:
a.size

10

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [47]:
b = np.arange(20, 1, -2)
b = b.reshape(-1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [48]:
b.shape # разница в форме

(1, 10)

In [55]:
b.size

10

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [63]:
a = np.zeros((3, 2))

a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [64]:
b = np.ones((2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [65]:
v = np.vstack((a, b))
v


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [66]:
v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [67]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
a = a.reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
At = a.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [79]:
b = a.dot(At)
b

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [78]:
b.size

1

In [80]:
b = np.linalg.det(b)

b

0.0

In [74]:
r = np.linalg.matrix_rank(b)
r

0

In [81]:
b_inv = np.linalg.inv(b)
b_inv

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [100]:
np.random.seed(42)
ar = np.random.random(2)
ar

array([0.37454012, 0.95071431])

In [98]:
np.random.seed(12)
ar1 = np.random.random(2)
ar1

array([0.15416284, 0.7400497 ])